export const codeThemeKeys = [
  "code",
  "codeBackground",
  "codeBorder",
  "codeComment",
  "codePunctuation",
  "codeNumber",
  "codeProperty",
  "codeTag",
  "codeClassName",
  "codeString",
  "codeSelector",
  "codeAttrName",
  "codeAttrValue",
  "codeEntity",
  "codeKeyword",
  "codeFunction",
  "codeStatement",
  "codePlaceholder",
  "codeInserted",
  "codeImportant",
  "codeConstant",
  "codeParameter",
  "codeOperator",
] as const;

export type CodeTheme = Record<(typeof codeThemeKeys)[number], string>;

export const codeThemes: Record<string, CodeTheme> = {
  paper: {
    code: "#2b2417",
    codeBackground: "#faf6ee",
    codeBorder: "#e7dfd0",
    codeComment: "#6f6552",
    codePunctuation: "#4a4235",
    codeNumber: "#8a4b00",
    codeProperty: "#8a4b00",
    codeTag: "#116329",
    codeClassName: "#7a3ea1",
    codeString: "#0a5f52",
    codeSelector: "#116329",
    codeAttrName: "#8a4b00",
    codeAttrValue: "#0a5f52",
    codeEntity: "#7a3ea1",
    codeKeyword: "#a41c2f",
    codeFunction: "#7a3ea1",
    codeStatement: "#a41c2f",
    codePlaceholder: "#6f6552",
    codeInserted: "#116329",
    codeImportant: "#a41c2f",
    codeConstant: "#8a4b00",
    codeParameter: "#2b2417",
    codeOperator: "#4a4235",
  },
  slate: {
    code: "#1f2933",
    codeBackground: "#f3f5f7",
    codeBorder: "#dbe1e8",
    codeComment: "#5c6b7a",
    codePunctuation: "#3e4c59",
    codeNumber: "#0b5fa5",
    codeProperty: "#0b5fa5",
    codeTag: "#0f7357",
    codeClassName: "#6b3fa0",
    codeString: "#0a5f52",
    codeSelector: "#0f7357",
    codeAttrName: "#0b5fa5",
    codeAttrValue: "#0a5f52",
    codeEntity: "#6b3fa0",
    codeKeyword: "#a01b3f",
    codeFunction: "#6b3fa0",
    codeStatement: "#a01b3f",
    codePlaceholder: "#5c6b7a",
    codeInserted: "#0f7357",
    codeImportant: "#a01b3f",
    codeConstant: "#0b5fa5",
    codeParameter: "#1f2933",
    codeOperator: "#3e4c59",
  },
  midnight: {
    code: "#dbe4f0",
    codeBackground: "#151a24",
    codeBorder: "#27303f",
    codeComment: "#8b9bb4",
    codePunctuation: "#c3cddb",
    codeNumber: "#f2b880",
    codeProperty: "#f2b880",
    codeTag: "#7fd6a8",
    codeClassName: "#8fd3f4",
    codeString: "#9fd8a0",
    codeSelector: "#7fd6a8",
    codeAttrName: "#f2b880",
    codeAttrValue: "#9fd8a0",
    codeEntity: "#8fd3f4",
    codeKeyword: "#8ab4ff",
    codeFunction: "#e6c98a",
    codeStatement: "#f39f9f",
    codePlaceholder: "#8b9bb4",
    codeInserted: "#9fd8a0",
    codeImportant: "#f39f9f",
    codeConstant: "#f2b880",
    codeParameter: "#dbe4f0",
    codeOperator: "#c3cddb",
  },
  plum: {
    code: "#e9e2f5",
    codeBackground: "#1e1726",
    codeBorder: "#332a40",
    codeComment: "#9b8fb0",
    codePunctuation: "#cfc5de",
    codeNumber: "#f0b3d0",
    codeProperty: "#f0b3d0",
    codeTag: "#8fe0c0",
    codeClassName: "#9fd7f0",
    codeString: "#f2dfa0",
    codeSelector: "#8fe0c0",
    codeAttrName: "#f0b3d0",
    codeAttrValue: "#f2dfa0",
    codeEntity: "#9fd7f0",
    codeKeyword: "#c9a4ff",
    codeFunction: "#8fe0c0",
    codeStatement: "#ff9fb0",
    codePlaceholder: "#9b8fb0",
    codeInserted: "#8fe0c0",
    codeImportant: "#ff9fb0",
    codeConstant: "#f0b3d0",
    codeParameter: "#e9e2f5",
    codeOperator: "#cfc5de",
  },
};

export function resolveCodeTheme(name: unknown): CodeTheme | undefined {
  return typeof name === "string" ? codeThemes[name] : undefined;
}
